version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    # Update all dependencies in a single PR.
    groups:
      rust-dependencies:
        patterns:
          - "*"
    # Include transitive dependencies.
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: "mongocrypt-sys"
      - dependency-name: "*"
        update-types: [version-update:semver-major]
