version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "mongodb/dbx-rust"
    # Only bump to the latest version compatible with the dependency's version
    # in Cargo.toml. This is the equivalent of running `cargo update`.
    versioning-strategy: lockfile-only
    # Update all dependencies in a single PR.
    groups:
      rust-dependencies:
        patterns:
          - "*"
    # Include transitive dependencies.
    allow:
      - dependency-type: all
